name: Run tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Initialize local.properties
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties

      - name: Decode Google Services JSON
        run: printf "%s" "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > app/google-services.json

      - name: Validate JSON
        run: jq . app/google-services.json

      - name: Run unit tests
        run: ./gradlew clean testDebug